Bloco_de_Notas/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_bloco.urls')),
]


if settings.DEBUG:
    urlpatterns += [
    path("ckeditor5/", include('django_ckeditor_5.urls'), name="ck_editor_5_upload_file"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

app_bloco/urls.py
from . import views
from django.urls import path

urlpatterns = [
    path('', views.HomeListView.as_view(), name='home'),
    path('criar_bloco/', views.criar_bloco, name='novo_bloco'),
    path('criar_tema/', views.criar_tema, name='novo_tema'),
    path('detalhes/<int:bloco_id>/', views.ler_bloco, name='detalhes'),
    path('update_bloco/<int:bloco_id>/', views.editar_bloco, name='update_bloco'),
    path('update_tema/<int:tema_id>/', views.editar_tema, name='update_tema'),
    path('deletar_bloco/<int:bloco_id>/', views.deletar_bloco, name='deletar_bloco'),
    path('deletar_tema/<int:tema_id>/', views.deletar_tema, name='deletar_tema'),
    path('temas/', views.temas, name='temas'),
    path('blocos/', views.BlocosListView.as_view(), name='blocos'),
    path('search/', views.SearchResultsView.as_view(), name='search_results'),
    
    
]

app_bloco/models.py
from django.db import models
from django.utils import timezone
from django_ckeditor_5.fields import CKEditor5Field


class Tema(models.Model):
    tema = models.CharField(max_length=255)
    
    def __str__(self):
        return self.tema
    


class BlocoNota(models.Model):
    titulo = models.CharField(max_length=255)
    assunto = models.CharField(max_length=255)
    tema = models.ForeignKey(Tema, related_name='tema_bloco' ,on_delete=models.CASCADE)
    conclusao = CKEditor5Field('Text', config_name='extends')
    data_criada = models.DateTimeField(auto_now_add=True)
    

    
    def __str__(self):
        return self.titulo
    
    
    class Meta:
        verbose_name = 'BlocoNota'
        verbose_name_plural = 'BlocosNotas'
        ordering = ['-data_criada']
        
        
    @property
    def days_ago(self):
        current_date = timezone.now()
        difference = current_date - self.data_criada
        return difference.days

    
    @property
    def hours_minutes_ago(self):
        current_date = timezone.now()
        difference = current_date - self.data_criada
        minutes, _ = divmod(difference.seconds, 60)
        if difference.days >= 1:
            return f"{difference.days} dias"
        elif difference.seconds >= 3600:
            return f"{difference.seconds // 3600} horas"
        else:
            return f"{minutes} minutos"
        
    @property 
    def fitro_temas(self):
        
        listas_temas = []
        
        temas = Tema.objects.all()
        
        for tem in temas:
            listas_temas.append(tem)
        
        
        # ainda não terminei
        return listas_temas
   
    
    

app_bloco/forms.py
from django import forms
from .models import BlocoNota, Tema

class Criar_bloco(forms.ModelForm):
    class Meta:
        model = BlocoNota
        fields = ('titulo', 'assunto', 'tema', 'conclusao')


class Criar_Tema(forms.ModelForm):
    class Meta:
        model = Tema
        fields = ('tema',)
        
        

app_bloco/views.py
from typing import Any
from django.shortcuts import render, redirect, get_object_or_404
from .models import BlocoNota, Tema
from django.views import generic
from .forms import Criar_bloco, Criar_Tema
from django.db.models import Q


class HomeListView(generic.ListView):
    model = BlocoNota
    template_name = 'home.html'
    context_object_name = 'bloco_list'
    paginate_by = 3 # numero de elementos exibidos por paginas
    
    def get_queryset(self):
        return BlocoNota.objects.order_by('-data_criada')
    
    
    

class BlocosListView(generic.ListView):
    model = BlocoNota
    template_name = 'blocos.html'
    context_object_name = 'bloco_list'
    paginate_by = 8 # numero de elementos exibidos por paginas
    
    
    def get_queryset(self):
        query = self.request.GET.get('tema')
        if query:
            return BlocoNota.objects.filter(Q(tema=query)).order_by('-data_criada')
        else:
            return BlocoNota.objects.order_by('-data_criada')



class SearchResultsView(generic.ListView):
    model = BlocoNota
    template_name = 'search_results.html'
    context_object_name = 'bloco_list'
    paginate_by = 3

    def get_queryset(self):
        query = self.request.GET.get('search')
        if query:
            return BlocoNota.objects.filter(
                Q(titulo__icontains=query) | Q(conclusao__icontains=query)
            ).order_by('-data_criada')
        else:
            return BlocoNota.objects.none()  # Retorna uma queryset vazia se não houver consulta    




def criar_bloco(request):
    if request.method == 'POST':
        form = Criar_bloco(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = Criar_bloco()            

    return render(request, 'forms/criar_bloco.html', {'form': form})



def ler_bloco(request, bloco_id):
    bloco = get_object_or_404(BlocoNota, pk=bloco_id)
    return render(request, 'detalhes.html', {'bloco': bloco})
    



def editar_bloco(request, bloco_id):
    bloco = get_object_or_404(BlocoNota, pk=bloco_id)
    
    if request.method == "POST":
        form = Criar_bloco(request.POST, instance=bloco)
        if form.is_valid():
            form.save()
            return redirect('detalhes', bloco_id=bloco_id)
    else:
        form = Criar_bloco(instance=bloco)
        
    return render(request, 'forms/update/update_bloco.html', {'form': form})



def deletar_bloco(request, bloco_id):
    bloco = get_object_or_404(BlocoNota, pk=bloco_id)
    bloco.delete()
    return redirect('home')




def criar_tema(request):
    if request.method == 'POST':
        form = Criar_Tema(request.POST)
        if form.is_valid():
            form.save()
            return redirect('home')
    else:
        form = Criar_Tema()
        
    return render(request, 'forms/criar_tema.html', {'form': form})




def temas(request):
    temas = Tema.objects.all()
    return render(request, 'temas.html', {"temas": temas})


def ler_tema(request, tema_id):
    pass




def editar_tema(request, tema_id):
    tema = get_object_or_404(Tema, pk=tema_id)

    if request.method == 'POST':
        form = Criar_Tema(request.POST, instance=tema)
        if form.is_valid():
            form.save()
            return redirect('temas')
    else:
        form = Criar_Tema(instance=tema)
    
    return render(request, 'forms/update/update_tema.html', {'form': form})




#Criar um modal para verficar se usuario quer mudar sim ou não
def deletar_tema(request, tema_id):
    tema = get_object_or_404(Tema, pk=tema_id)
    tema.delete()
    return redirect('temas')




'''class BlocosListView(generic.ListView):
    model = BlocoNota
    template_name = 'blocos.html'
    context_object_name = 'bloco_list'
    paginate_by = 8 # numero de elementos exibidos por paginas
    
    def get_queryset(self):
        query = self.request.GET.get('search')
        if query:
            return BlocoNota.objects.filter(Q(tema__icontains=query)).order_by('-data_criada')
        else:
            return BlocoNota.objects.none()
    
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        temas = Tema.objects.all()
        context = {'temas': temas}
        return context'''

app_bloco/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Bloco de notas</title>
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/bootstrap.min.css.map' %}" rel="stylesheet">



  <!-- Custom styles for this template -->
</head>


<body>

  <style>
    body {
      font-size: 17px;
      background-color: #fdfdfd;
      margin: 0;
      padding: 0;
      box-sizing: border-box;
      margin-bottom: 20px;
    }
    
    

    .navbar {
    margin-bottom: 20px;
    }


    .mt-5 {
      margin-top: 0rem !important;
    }

    /*.py-3 {
            padding-top: 23rem !important;
        }*/

        .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .nav-scroller .nav {
        display: flex;
        flex-wrap: nowrap;
        padding-bottom: 1rem;
        margin-top: -1px;
        overflow-x: auto;
        text-align: center;
        white-space: nowrap;
        -webkit-overflow-scrolling: touch;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }
      .bd-mode-toggle {
        z-index: 1500;
      }
  </style>


  <nav class="navbar navbar-dark bg-dark" aria-label="Dark offcanvas navbar">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">Super Notas</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbarDark" aria-controls="offcanvasNavbarDark" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbarDark" aria-labelledby="offcanvasNavbarDarkLabel">
        <div class="offcanvas-header">
          <h5 class="offcanvas-title" id="offcanvasNavbarDarkLabel">Offcanvas</h5>
          <button type="button" class="btn-close btn-close-white" data-bs-dismiss="offcanvas" aria-label="Close"></button>
        </div>
        <div class="offcanvas-body">
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'temas' %}">Temas</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'blocos' %}">Blocos</a>
            </li>
          </ul>
          <form action="{% url 'search_results' %}" method="get" class="d-flex mt-3" role="search">
            <input class="form-control me-2" type="text" aria-label="Pesquisar" name="search" placeholder="Pesquisar">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </div>
  </nav>


  {% block content %}

  {% endblock content %}
  <!-- Footer -->

  <!-- Footer -->
  <footer class="footer fixed-bottom bg-dark py-0">
    <div class="container text-center text-white">
      Copyright &copy; Django Central
    </div>
  </footer>
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

app_bloco/templates/blocos.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<style>
    /* Estilo personalizado para centralizar o texto */
    .center-text {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
</style>



<div class="album py-5 bg-body-tertiary">
  <h1 class="text-center text-dark h1">Todos blocos de anotações</h1>
      <div class="container">
  </div>
</div>


<div class="album py-5 bg-body-tertiary">
  <div class="container">
      <!-- ... Filtros ... -->
      <form method="get" action="{% url 'blocos' %}" class="mt-3">
          <div class="row g-3"> 
          <div class="col-md-4">
              <label for="id_tema">Todos blocos:</label>
              <select id="id_tema" name="tema" class="form-select">
                  <option value="" {% if not categoria_selecionada %}selected{% endif %}>Todas as categorias</option>
                {% for opcao in bloco_list.fitro_temas %}

                <option value="{{ opcao.tema }}" {% if categoria_selecionada == '{{ opcao.tema }}' %}selected{% endif %}>{{ opcao.tema }}</option>

                {% endfor %}
              </select>
          </div>

          <div><input type="submit" value="Filtrar"></div>
      </form>
  </div>
</div>




{% if bloco_list %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
  
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      
  
      {% for bloco in bloco_list %}
        
          
              <div class="col">
                <div class="card">
                  <div class="card-header">
                    Bloco de notas
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">{{ bloco.titulo }}</h5>
                    <p class="card-text">{{ bloco.assunto }}</p>
                    <a href="{% url 'detalhes' bloco_id=bloco.id %}" class="btn btn-primary">Detalhes</a>
                  </div>
                  <div class="card-footer text-body-secondary">
                    {{ bloco.hours_minutes_ago }}
                  </div>
                </div>
              </div>    
      {% endfor %}
      {% else %}
            
      <div class="container py-2 text-center">
        <h2 class="fw-light center-text">Nenhum resultado encontrado.</h2>
        </div>

      {% endif %}
      </div>
    </div>
  </div>


{% if is_paginated %}
<nav aria-label="Page navigation conatiner"></nav>
<ul class="pagination justify-content-center">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %} 
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
    {% endif %}
{% endif %}
</ul>
</nav>
</div>
{% endblock %}

app_bloco/templates/detalhes.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }

    .b-example-divider {
      width: 100%;
      height: 3rem;
      background-color: rgba(0, 0, 0, .1);
      border: solid rgba(0, 0, 0, .15);
      border-width: 1px 0;
      box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
    }

    .b-example-vr {
      flex-shrink: 0;
      width: 1.5rem;
      height: 100vh;
    }

    .bi {
      vertical-align: -.125em;
      fill: currentColor;
    }

    .nav-scroller {
      position: relative;
      z-index: 2;
      height: 2.75rem;
      overflow-y: hidden;
    }

    .nav-scroller .nav {
      display: flex;
      flex-wrap: nowrap;
      padding-bottom: 1rem;
      margin-top: -1px;
      overflow-x: auto;
      text-align: center;
      white-space: nowrap;
      -webkit-overflow-scrolling: touch;
    }

    .btn-bd-primary {
      --bd-violet-bg: #712cf9;
      --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

      --bs-btn-font-weight: 600;
      --bs-btn-color: var(--bs-white);
      --bs-btn-bg: var(--bd-violet-bg);
      --bs-btn-border-color: var(--bd-violet-bg);
      --bs-btn-hover-color: var(--bs-white);
      --bs-btn-hover-bg: #6528e0;
      --bs-btn-hover-border-color: #6528e0;
      --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
      --bs-btn-active-color: var(--bs-btn-hover-color);
      --bs-btn-active-bg: #5a23c8;
      --bs-btn-active-border-color: #5a23c8;
    }
    .bd-mode-toggle {
      z-index: 1500;
    }
  </style>


    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="arrow-right-circle" viewBox="0 0 16 16">
          <path d="M8 0a8 8 0 1 1 0 16A8 8 0 0 1 8 0zM4.5 7.5a.5.5 0 0 0 0 1h5.793l-2.147 2.146a.5.5 0 0 0 .708.708l3-3a.5.5 0 0 0 0-.708l-3-3a.5.5 0 1 0-.708.708L10.293 7.5H4.5z"/>
        </symbol>
        <symbol id="bootstrap" viewBox="0 0 118 94">
          <title>Bootstrap</title>
          <path fill-rule="evenodd" clip-rule="evenodd" d="M24.509 0c-6.733 0-11.715 5.893-11.492 12.284.214 6.14-.064 14.092-2.066 20.577C8.943 39.365 5.547 43.485 0 44.014v5.972c5.547.529 8.943 4.649 10.951 11.153 2.002 6.485 2.28 14.437 2.066 20.577C12.794 88.106 17.776 94 24.51 94H93.5c6.733 0 11.714-5.893 11.491-12.284-.214-6.14.064-14.092 2.066-20.577 2.009-6.504 5.396-10.624 10.943-11.153v-5.972c-5.547-.529-8.934-4.649-10.943-11.153-2.002-6.484-2.28-14.437-2.066-20.577C105.214 5.894 100.233 0 93.5 0H24.508zM80 57.863C80 66.663 73.436 72 62.543 72H44a2 2 0 01-2-2V24a2 2 0 012-2h18.437c9.083 0 15.044 4.92 15.044 12.474 0 5.302-4.01 10.049-9.119 10.88v.277C75.317 46.394 80 51.21 80 57.863zM60.521 28.34H49.948v14.934h8.905c6.884 0 10.68-2.772 10.68-7.727 0-4.643-3.264-7.207-9.012-7.207zM49.948 49.2v16.458H60.91c7.167 0 10.964-2.876 10.964-8.281 0-5.406-3.903-8.178-11.425-8.178H49.948z"></path>
        </symbol>
      </svg>
      
      <div class="col-lg-8 mx-auto p-4 py-md-5">
        <header class="d-flex align-items-center pb-3 mb-5 border-bottom">
          <a href="/" class="d-flex align-items-center text-body-emphasis text-decoration-none">
            <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"/></svg>
            <span class="fs-4">{{ bloco.titulo }}</span>
          </a>
        </header>
      
        <main>
          <h1 class="text-body-emphasis">{{ bloco.assunto }}</h1>
          <p class="fs-5 col-md-8">{{ bloco.conclusao | safe }}</p>
      
          <div class="mb-5">
            <a href="{% url 'update_bloco' bloco_id=bloco.id %}" class="btn btn-primary btn-lg px-4">Editar</a>
            <a href="{% url 'deletar_bloco' bloco_id=bloco.id %}" class="btn btn-danger btn-lg px-4">Apagar</a>
          </div>
          <hr class="col-3 col-md-2 mb-5">

          
        </main>

{% endblock %}

app_bloco/templates/forms/criar_bloco.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<h1 class="text-center text-primary display-4" style="margin: 50px 20px 50px 20px;">Criar Novo Bloco</h1>
    <form method="post" class="container" style="max-width: 800px;">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>

    {% endblock %}

app_bloco/templates/forms/criar_tema.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}

<h1 class="text-center text-primary display-4" style="margin: 50px 20px 50px 20px;">Criar Novo tema</h1>
    <form method="post" class="container" style="max-width: 400px;">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Adicionar</button>
      </form>


{% endblock %}

app_bloco/templates/forms/update/update_bloco.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<h1 class="text-center text-primary display-4" style="margin: 50px 20px 50px 20px;">Editar</h1>

    <form method="post" class="container" style="max-width: 800px;">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>



{% endblock %}

app_bloco/templates/forms/update/update_tema.html
{% extends "base.html" %}

{% load static %}

{% load crispy_forms_tags %}

{% block content %}
<h1 class="text-center text-primary display-4" style="margin: 50px 20px 50px 20px;">Editar</h1>
    <form method="post" class="container" style="max-width: 400px;">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="btn btn-primary">Adicionar</button>
    </form>



{% endblock %}

app_bloco/templates/home.html
{% extends "base.html" %}

{% load static %}

{% block content %}


<style>
  /* Estilo personalizado para centralizar o texto */
  .center-text {
      position: absolute;
      top: 75%;
      left: 50%;
      transform: translate(-50%, -50%);
  }
</style>



<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">Blocos de notas</h1>
      <p class="lead text-body-secondary">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don’t simply skip over it entirely.</p>
      <p>
        <a href="{% url 'novo_bloco' %}" class="btn btn-primary my-2">Novo Bloco de Notas</a>
        <a href="{% url 'novo_tema' %}" class="btn btn-secondary my-2">Novo tema</a>
      </p>
    </div>
  </div>
</section>

{% if bloco_list %}

<div class="album py-7 bg-body-tertiary">
    <div class="container mb-5">
  
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      
  
      {% for bloco in bloco_list %}
        
          
              <div class="col">
                <div class="card">
                  <div class="card-header">
                    Bloco de notas
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">{{ bloco.titulo }}</h5>
                    <p class="card-text">{{ bloco.assunto }}</p>
                    <a href="{% url 'detalhes' bloco_id=bloco.id %}" class="btn btn-primary">Detalhes</a>
                  </div>
                  <div class="card-footer text-body-secondary">
                    {{ bloco.hours_minutes_ago }}
                  </div>
                </div>
              </div>    
      {% endfor %}
      {% else %}
            
      <div class="container py-2 text-center">
        <h2 class="fw-light center-text">Nenhum resultado encontrado.</h2>
        </div>

      {% endif %}
      </div>
    </div>
  </div>  


{% if is_paginated %}
<nav aria-label="Page navigation conatiner">
<ul class="pagination justify-content-center mb-5">
    {% if page_obj.has_previous %}
    <li><a href="?page={{ page_obj.previous_page_number }}" class="page-link">&laquo; PREV </a></li>
    {% endif %} 
    {% if page_obj.has_next %}
    <li><a href="?page={{ page_obj.next_page_number }}" class="page-link"> NEXT &raquo;</a></li>
    {% endif %}
{% endif %}
</ul>
</nav>
</div>
{% endblock %}

app_bloco/templates/search_results.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<style>
    /* Estilo personalizado para centralizar o texto */
    .center-text {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
    }
</style>


<h1 class="mb-4 display-4 text-center">Resultados da Pesquisa</h1>

{% if bloco_list %}

<div class="album py-5 bg-body-tertiary">
    <div class="container">
  
      <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
      
  
      {% for bloco in object_list %}
        
          
              <div class="col">
                <div class="card">
                  <div class="card-header">
                    Bloco de notas
                  </div>
                  <div class="card-body">
                    <h5 class="card-title">{{ bloco.titulo }}</h5>
                    <p class="card-text">{{ bloco.assunto }}</p>
                    <a href="{% url 'detalhes' bloco_id=bloco.id %}" class="btn btn-primary">Detalhes</a>
                  </div>
                  <div class="card-footer text-body-secondary">
                    {{ bloco.hours_minutes_ago }}
                  </div>
                </div>
              </div>    
      {% endfor %}
      {% else %}
            
      <div class="container py-2 text-center">
        <h2 class="fw-light center-text">Nenhum resultado encontrado.</h2>
        </div>

      {% endif %}
      </div>
    </div>
  </div>


{% endblock %}

app_bloco/templates/temas.html
{% extends "base.html" %}

{% load static %}

{% block content %}
<div class="bd-example-snippet bd-code-snippet"><div class="bd-example m-0 border-0">
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col">Temas</th>
                <th scope="col">Editar</th>
                <th scope="col">Delatar</th>
              </tr>
              </thead>
    {% for tema in temas %}
    
          
          <tbody>
          
          <tr class="table-primary">
            <th scope="row">{{ tema.tema }}</th>
            <td><a href="{% url 'update_tema' tema_id=tema.id %}" class="btn btn-success btn-bg px-4">Editar</a></td>
            <td><a href="{% url 'deletar_tema' tema_id=tema.id %}" class="btn btn-danger btn-bg px-3">Apagar</a></td>
          </tr>
          
         
    {% endfor %}
</tbody>
</table>
</div></div>

    
    



{% endblock %}